all:
	mips-linux-gnu-gcc -EB -o boole boole.c
	mips-linux-gnu-gcc -EB -o pop pop.c
	mips-linux-gnu-gcc -EB -o sparse sparse.c
	mips-linux-gnu-gcc -EB -o snoob snoob.c
	mips-linux-gnu-gcc -EB -o hamming hamming.c
	
